import Foundation

enum AppStringKey: String, CaseIterable, Sendable {
    case appName
    case jobs
    case settings
    case jenkins
    case notifications
    case serverURL
    case serverURLHelp
    case username
    case apiToken
    case apiTokenHelp
    case permissionsHelp
    case refreshInterval
    case seconds
    case testConnection
    case connectionSuccessful
    case connectionChangeWarning
    case save
    case saved
    case language
    case notificationPermission
    case requestPermission
    case sendTestNotification
    case openSystemSettings
    case monitoringNote
    case notificationTestBody
    case notificationsEnabled
    case notifyBuildStarted
    case notifyBuildSucceeded
    case notifyBuildFailed
    case notifyBuildRecovered
    case playSound
    case refresh
    case loadingJobs
    case noJobs
    case configureJenkins
    case openSettings
    case openInJenkins
    case detailView
    case cardView
    case searchJobs
    case status
    case lastBuild
    case lastCompletedBuild
    case lastSuccessfulBuild
    case lastFailedBuild
    case buildNumber
    case startedAt
    case duration
    case inQueue
    case yes
    case no
    case closeTab
    case jobDetails
    case noBuilds
    case loadingJob
    case retry
    case online
    case offline
    case updatedNow
    case monitoredJobs
    case eventStarted
    case eventSucceeded
    case eventFailed
    case eventRecovered
    case notificationBuildWithNumber
    case notificationBuildWithoutNumber
    case quit
    case about
    case general
    case connectionError
    case unknownStatus
    case statusSuccess
    case statusFailure
    case statusUnstable
    case statusAborted
    case statusNotBuilt
    case statusDisabled
    case statusBuilding
}
